name: Test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependensiyalarni o'rnatish
        run: npm ci
      - name: Linterni ishga tushirish
        run: npm run lint

  test:
    needs: [lint]
    strategy:
      matrix:
        node-version: [16,18,20,22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node versiyasini sozlash
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependensiyalarni o'rnatish
        run: npm ci
      - name: Testlarni ishga tushirish
        env:
          PORT: ${{ secrets.PORT }}
        run: npm run test
